server:
  port: 8089
spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8084/
          predicates:
            - Path=/service1/**
        - id: Microservice2
          uri: http://localhost:8085/
          predicates:
            - Path=/service2/**
        - id: Microservice3
          uri: http://localhost:9090/
          predicates:
            - Path=/tasks/**